### ISSUE TITLE
Decorative Planks/Wood Tagged as Planks

### ISSUE THREAD

**Issue by Darkosto** [Day-Dreamers-Dev/Crumbs#10]
## Is there a related problem?

Many of the decorative blocks are 1 to 1 crafting with vanilla planks. Is it possible to tag your blocks so they can be used in recipes needed `minecraft:planks`? This would help users skip a step to convert the blocks back to normal blocks.

Thanks!

**Comment by Trikzon** [comment]
Thanks for reporting :)

I just released v1.0.7 that adds Crumbs' wooden tiles and reinforced planks to the `minecraft:planks` tag.

I also added some of our other blocks to other tags. For a full list, take a look at the changelog: https://github.com/dodogang/crumbs/releases
