### ISSUE TITLE
Crafting Table Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Day-Dreamers-Dev/Crumbs#4]
## Expected Behavior
 
- No crashes

## Current Behavior

- Right-clicking the custom crafting tables crashes the server.
- [Crash Report](https://gist.github.com/WenXin20/ec9db255a9525d88669e379d9e109a72)

## Possible Solution

- Check for client only.

## Steps to Reproduce

1. Place modded crafting table
2. Crash

## Context (Environment)

`Minecraft v1.16.4`
`Forge v35.1.13`
`Crumbs v1.0.5`

**Comment by Trikzon** [comment]
I have just tested this on a server and have no crashes/problems.
Also, I don't see any obvious client-only code and it's the same code we've used since the crafting tables were implemented.

I see you have a lot of mods installed, would it be possible for you to test it without them?

**Comment by WenXin20** [comment]
Hmm, it might be related to Polymorph or Crafting Tweaks, those are the only two mods that I can think of that change crafting tables. But I can try without other mods tomorrow.

**Comment by Trikzon** [comment]
I just tested it with polymorph, and that's the problem. I'll look into what exactly is causing it. Thanks for reporting :)

**Comment by WenXin20** [comment]
Thanks! Glad I didn't have to sort through all the mods I had!

**Comment by Trikzon** [comment]
I can't figure out what the issue is so I contacted the polymorph devs. Hopefully we can get this solved soon.
https://github.com/TheIllusiveC4/Polymorph/issues/47

**Comment by Trikzon** [comment]
So after further investigation and the help of Shadew, one of the team members, the issue is actually in the build system that we use, Architect.
Shadew reported the bug here: https://github.com/architectury/architect-plugin/issues/1
I'll be trying a temporary solution to the problem now.

**Comment by WenXin20** [comment]
Alright, thanks
