### ISSUE TITLE
Barrels missing piglin tag

### ISSUE THREAD

**Issue by WenXin20** [Day-Dreamers-Dev/Crumbs#5]
`Crumbs v1.0.6`
`Minecraft v1.16.4`
`Forge v35.1.28`

Barrels are missing the block tag `minecraft:guarded_by_piglins`.

**Comment by Trikzon** [comment]
I didn't know that tag existed. I'll add it to the next release!

**Comment by WenXin20** [comment]
Thanks! I just found it too and noticed a lot of mods missed it as well.

**Comment by Trikzon** [comment]
v1.0.7 was just released that solves this issue. Thank you for reporting :)
