### ISSUE TITLE
Crash on using Crafting Table [1.16.4, Forge]

### ISSUE THREAD

**Issue by Capaldi12** [Day-Dreamers-Dev/Crumbs#6]
I've just installed mod and tried to use Spruce Crafting Table, but as soon as I right-clicked it game froze and then crashed.
[Crash log](https://pastebin.com/rZwmqcvB)

I deleted all mods and created new world, but same crash was encountered. 

I am on Minecraft 1.16.4 and used version for 1.16.4

**Comment by FoxSamu** [comment]
Known issue, probably fixed already

**Comment by FoxSamu** [comment]
Marked as duplicate of #4, thanks for the report though

**Comment by Trikzon** [comment]
As Shadew said, this should be fixed in the latest Crumbs version. If you are on the latest (v1.0.6), then let us know.

**Comment by Capaldi12** [comment]
Yeah, works fine, thanks!
