### ISSUE TITLE
Tag Workbenches so they work in mod recipes

### ISSUE THREAD

**Issue by KnightMiner** [Day-Dreamers-Dev/Crumbs#9]
## Is there a related problem?
Other mods make use of the vanilla crafting table in recipes, but this mod prevents crafting it with most woods.

## Describe the solution you'd like

Tag your new workbenches using `forge:workbenches`. That is what Tinkers Construct will use for its recipe instead of just the vanilla table.

## Describe alternatives you have considered
You could just add a crafting recipe to craft the vanilla table from your table. However the tag is better

**Comment by Trikzon** [comment]
Our crafting tables have just been added to the forge workbenches tag in v1.0.7. Thank you for reporting :)
